# Generated by Django 2.2.14 on 2020-07-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
